[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[variables]
NODE_ENV = "production"
COREPACK_INTEGRITY_KEYS = "0"

[phases.install]
cmds = [
  "corepack enable",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
"pnpm --filter @ads/shared build",
"pnpm --filter @ads/api build",
"pnpm --filter @ads/worker build",
"pnpm --filter @ads/web build"
]

# N√ÉO DEFINA START AQUI
